export const LOGIN_REQUEST = "LOGIN_REUESTQ";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const SIGNUP_REQUEST = "SIGNUP_REUESTQ";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

export const FORGOT_EMAIL_REQUEST = "FORGOT_EMAIL_REQUEST";

export const RESET_REQUEST = "LOGIN_REUESTQ";
export const RESET_SUCCESS = "LOGIN_SUCCESS";
export const RESET_ERROR = "LOGIN_ERROR";
